apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: monitoring
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data
