apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc2
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage

